# Generated by Django 5.2.6 on 2025-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('datetime_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
    ]
